name: Linux Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: Install Boost
      uses: MarkusJx/install-boost@v2.4.0
      with:
        boost_version: 1.73.0
      
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Checkout
      uses: actions/checkout@v2.4.2

    - name: Clone testing repo
      run: |
        echo "$PWD"
        cd /home/runner/work/Ardutask
        git clone -b linux_modifications https://github.com/15jgme/Ardutask-demo-project.git
      
    - name: Import Ardutask
      run: |
        cp -r /home/runner/work/Ardutask/Ardutask /home/runner/work/Ardutask/Ardutask-demo-project/lib


    - name: Run PlatformIO
      run: |
        cd /home/runner/work/Ardutask/Ardutask-demo-project
        pio lib --global install PlatformHelpers
        pio run --environment linux
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
