name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Checkout
      uses: actions/checkout@v2.4.2

    - name: Clone testing repo
      run: |
        cd D:/a/Ardutask
        git clone https://github.com/15jgme/Ardutask-demo-project.git
    - name: This is a bad thing
      run: |
        cd D:/a/
        tree
      
    - name: Import Ardutask
      run: |
        cd D:/a/Ardutask/Ardutask-demo-project/lib
        echo $GITHUB_WORKSPACE
        echo GITHUB_WORKSPACE
        cp GITHUB_WORKSPACE .
        cd ..

    - name: Run PlatformIO
      run: pio run --environment native
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
