name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        example: [a/Ardutask/Ardutask/Tests/test1.cpp]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci -e native -c ./lib/Ardutask/Tests/platformio.ini ./lib/Ardutask/Tests/test1.cpp
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
